### ISSUE TITLE
关机的时候的保存和恢复

### ISSUE THREAD

**Issue by mcxinyu** [xiaoqiAndroid/AutoSave#2]
关机的时候调用的两个方法没有相应的实现么？

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState, @Nullable PersistableBundle persistentState) {
        super.onCreate(savedInstanceState, persistentState);
    }

    @Override
    public void onSaveInstanceState(Bundle outState, PersistableBundle outPersistentState) {
        super.onSaveInstanceState(outState, outPersistentState);
    }

**Comment by JavaNoober** [comment]
暂时只能存入Bundle还不支持PersistableBundle，多谢提醒，下个版本加上

**Comment by JavaNoober** [comment]
更新到2.1.0增加了对PersistableBundle的支持
